### ISSUE TITLE
[FeatureRequest] mount additional files to proxy in declaration way

### ISSUE THREAD

**Issue by zhiyanliu** [aws/aws-app-mesh-inject#126]
Currently appmesh injector doesn't allow the operator to add files to the proxy in declaration way,
especially in TLS configuring case, operator either has to build an own envoy docker image with additional cert and key files or add the own
script to download these file from a middle service, e.g. AWS Secrets Manager, or even both. The example at [0][1] shows this inconvenient operation pattern. IMO we need an easier and "k8s" way to do this automatically by appmesh injector.

[0] https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-tls-file-provided/src/customEnvoyImage/entryPoint.sh#L5
[1] https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-tls-file-provided/src/customEnvoyImage/deploy.sh

**Comment by zhiyanliu** [comment]
Hi folks, I just committed my draft PR for you take a review, and hope this idea works for the upstream as well. Thanks!

This enhancement really saved me a lot of time to prepare envoy image manually, especially there are some different microservices need to communicate each other with own certs, ca, keys in TLS way... terrible.

I verified it in my local EKS env (v1.14.9-eks-502bfb) in different cases. I'd like to add such essential unit test cases after we are in the page on the idea and the implement way.

One "limit" is that, with this change operator need to use the new annotation "appmesh.k8s.aws/configMapMounts" to attach any volume to the pod, appmesh injector will overwrite the `Volume` resource of the pod by the annotation config.

**Comment by zhiyanliu** [comment]
Hello @bcelenza and @jamsajones,

Sorry for interrupt. I see you're working in AWS App Mesh service team and shipped/proposed TLS traffic with ACM/own managed cert feature recently. May I have your idea and inputs on this proposal and PR? Thanks!

**Comment by bcelenza** [comment]
Hey @zhiyanliu, wouldn't exposing the certificate as a Secret make more sense in the context of a TLS certificate? I'm concerned about the security of a certificate's private key when provided directly into a ConfigMap.

**Comment by zhiyanliu** [comment]
Hi @bcelenza,

Got, I have update the patch to leverage secret instead of ConfigMap.

**Comment by bcelenza** [comment]
@zhiyanliu Thanks for the contribution! Should be merged and available in our upcoming release.

**Comment by zhiyanliu** [comment]
@bcelenza yrw, glad to help users with you all supports, thanks!
