### ISSUE TITLE
Support for X-Ray daemon as a sidecar

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-app-mesh-inject#29]
In order to use X-Ray, we'd need to extend the webhook to inject the X-Ray daemon as a sidecar. See for example [this ECS definition](https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/xray-container.json) from the examples.

Note that, AFAICT, this depends on PR #28 being applied.

**Comment by kiranmeduri** [comment]
Started work on this here https://github.com/kiranmeduri/aws-app-mesh-inject/tree/xray. Code is ready but need to verify it in an end-to-end scenario.

**Comment by bnusunny** [comment]
A more common way is to deploy X-Ray daemon on each node to save resources. Not sure which use case require to inject X-Ray daemon as sidecar?

**Comment by kiranmeduri** [comment]
@bnusunny, I agree that x-ray daemon as daemon-set is common approach (https://github.com/aws-samples/aws-xray-kubernetes). To avoid config being a one-way door we can have a separate flag to control injecting xray-daemon control, say EnableXrayInjection (or better name). In future we can introduce XrayDaemonAddress (string) that can point to a on-node xray-daemon using K8s service discovery. Would love some consensus on this.

**Comment by bnusunny** [comment]
Yeah, I agree daemon-per-pod approach will provide good first day experience. I also like to be able to configure this behavior, so that I can switch to daemon-per-node and have good 2nd day experience. 

@kiranmeduri  I agree what you suggested is a good approach.

**Comment by mhausenblas** [comment]
Thanks for #30 and #34 @kiranmeduri and I gave it a try, but doesn't work as I hoped, I'm afraid. A couple of things (not sure how best to fix it but here are the reasons it doesn't work):

* In [install.sh](https://github.com/aws/aws-app-mesh-inject/blob/master/hack/install.sh#L29) we've pinned the template to `v0.1.0` which doesn't have the new environment variables in the command.
* Per our README, users can enable X-Ray integration by setting `INJECT_XRAY_SIDECAR=true` but in [install.sh](https://github.com/aws/aws-app-mesh-inject/blob/master/hack/install.sh#L41) we overwrite that to `false`. I think we can simply comment out these lines (since the default is `false` anyways).

That's what I found so far, there might be other deps I've overlooked. Now, maybe it would be a good thing to simply release a new version, say `v0.1.1`, with these things fixed? WDYT?

**Comment by jqmichael** [comment]
> Thanks for #30 and #34 @kiranmeduri and I gave it a try, but doesn't work as I hoped, I'm afraid. A couple of things (not sure how best to fix it but here are the reasons it doesn't work):
> 
> * In [install.sh](https://github.com/aws/aws-app-mesh-inject/blob/master/hack/install.sh#L29) we've pinned the template to `v0.1.0` which doesn't have the new environment variables in the command.
> * Per our README, users can enable X-Ray integration by setting `INJECT_XRAY_SIDECAR=true` but in [install.sh](https://github.com/aws/aws-app-mesh-inject/blob/master/hack/install.sh#L41) we overwrite that to `false`. I think we can simply comment out these lines (since the default is `false` anyways).
> * We are using `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-app-mesh-inject:v0.1.0` container image which doesn't have the new code.
> 
> That's what I found so far, there might be other deps I've overlooked. Now, maybe it would be a good thing to simply release a new version, say `v0.1.1`, with these things fixed? WDYT?

Unfortunately, it is still a manual process today to release a new image, so that takes both time and  engineering efforts (the manual process requires peer review). @nckturner will be driving both injector and controller towards GA and I'm sure this is under his radar. 

To unblock, you can check out the repository and push to a personal repository.

**Comment by mhausenblas** [comment]
Thanks for the reply @jqmichael and I understand. Unfortunately to push to a personal repo doesn't work for me. My objective is to 1. make the [App Mesh with EKS walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs) working again (currently broken b/c of above), and 2. to add as a next step the X-Ray integration. So, while I appreciate it will take some time, I think we should prioritize cutting a new release, since the current state (docs here and in other places) and the artifacts and behavior are currently unfortunately not consistent, causing a sub-optimal DX.

**Comment by jqmichael** [comment]
> Thanks for the reply @jqmichael and I understand. Unfortunately to push to a personal repo doesn't work for me. My objective is to 1. make the [App Mesh with EKS walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs) working again (currently broken b/c of above), and 2. to add as a next step the X-Ray integration. So, while I appreciate it will take some time, I think we should prioritize cutting a new release, since the current state (docs here and in other places) and the artifacts and behavior are currently unfortunately not consistent, causing a sub-optimal DX.

Synced up with mhausenblas@ offline.  "App Mesh with EKS walkthrough" is no longer broken after his fix. @nckturner will release a new version of image to support x-ray by the end of this week.

**Comment by mhausenblas** [comment]
With https://github.com/aws/aws-app-mesh-inject/commit/fabbfa43dea5e6c25ba2dc43fb094d78f5b33e21 this has been addressed.
