### ISSUE TITLE
How to configure AWS X-Ray Variables 

### ISSUE THREAD

**Issue by bnusunny** [aws/aws-app-mesh-inject#31]
When I deploy X-Ray daemon on cluster nodes, I need to give Envoy to the connection information with the following environment variables. 

ENABLE_ENVOY_XRAY_TRACING
XRAY_DAEMON_PORT

How can I pass this information?

**Comment by mhausenblas** [comment]
For ECS, see [this example](https://github.com/aws/aws-app-mesh-examples/blob/fe81916dafe63aa84c9a60632183ff14df305c22/examples/apps/colorapp/ecs/envoy-container.json#L44) and also, `XRAY_DAEMON_PORT` defaults to `2000`, so you could use just this value.

**Comment by nckturner** [comment]
Using this helm chart, you can configure tracing: https://github.com/aws/eks-charts/tree/master/stable/appmesh-inject
