### ISSUE TITLE
Envoy default log level 

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-inject#33]
While running load tests on EKS I've noticed that the Envoy sidecar is responsible for 99% of a pod CPU usage. This due to the fact that Envoy log level is set to debug. I think logging should be disable by default.

**Comment by jqmichael** [comment]
I agree we shouldn't turn on `debug` level by default. Maybe `error` would be a better default value. 

https://github.com/envoyproxy/envoy/blob/master/source/common/common/logger.h#L78
