### ISSUE TITLE
Don't use latest for aws-appmesh-proxy-route-manager

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-inject#41]
We currently use latest for aws-appmesh-proxy-route-manager, which is dangerous.  We should pick a stable version.  

```
111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:latest
```

**Comment by bcelenza** [comment]
I believe this can be resolved with the merge of #45. Let me know if I'm wrong.
