### ISSUE TITLE
Invalid boolean value "" for -enable-statsd: parse error

### ISSUE THREAD

**Issue by tiborv** [aws/aws-app-mesh-inject#60]
Hi, Im getting:
```
Invalid boolean value "" for -enable-statsd: parse error
```
when `ENABLE_STATSD` is not set within the container.

Shouldn't it default to `false`? 

I.e: Shouldn't [this line](https://github.com/aws/aws-app-mesh-inject/blob/master/deploy/inject.yaml.template#L79) also set `false` as a default:
```
- -enable-statsd=${ENABLE_STATSD:-false}
```
like the other parameters for this container?

**Comment by tiborv** [comment]
Sorry, didnt see [this PR](https://github.com/aws/aws-app-mesh-inject/pull/56), closing this.

**Comment by jasonrichardsmith** [comment]
This is not fixed until it makes it into the release, since it only sits on the master branch.

the current README does not work.

**Comment by jamsajones** [comment]
Merged here https://github.com/aws/aws-app-mesh-inject/pull/56
