### ISSUE TITLE
stuck  at  "[source/server/server.cc:143] flushing stats"

### ISSUE THREAD

**Issue by zhuhesheng** [aws/aws-app-mesh-inject#65]
why stuck here?
![image](https://user-images.githubusercontent.com/9285333/61715228-3acdb880-ad8f-11e9-906d-35aab05da6af.png)
 and visit svc:
curl: (56) Recv failure: Connection reset by peer

**Comment by jamsajones** [comment]
If you are still having this issue please post to aws/aws-app-mesh-roadmap.
