### ISSUE TITLE
v0.1.5 injest Docker image does not exist

### ISSUE THREAD

**Issue by JoshArmi** [aws/aws-app-mesh-inject#68]
Tried installing via Option 2 as per the readme.

Unfortunately, it looks like the `v0.1.5` aws-app-mesh-inject image does not exist in the expected ECR repo.

I tried `docker pull`ing all tags for that image, but am not having any luck.

Did the ECR repo move?

Cheers

**Comment by nckturner** [comment]
Did you log into the registry before attempting to pull the image?  

```
aws ecr get-login --registry-ids 602401143452
```

**Comment by JoshArmi** [comment]
Sorry mate for tardiness, just giving that a crack now

Initially my EKS cluster was unable to get the container, which if I remember correctly is automatically authed to grab the required containers? Or at least that was how it worked previously.
