### ISSUE TITLE
TLS handshake Errors

### ISSUE THREAD

**Issue by streetmapp** [aws/aws-app-mesh-inject#71]
I'm running through examples for [App Mesh with EKS](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/eks). I'm not seeing any sidecar containers being created in my `appmesh-demo` namespace. Looking at the logs of the app-mesh-inject container I see the following.

```
2019/08/19 15:56:16 http: TLS handshake error from 100.113.129.235:46434: tls: first record does not look like a TLS handshake
2019/08/19 15:56:17 http: TLS handshake error from 100.113.129.235:46472: tls: first record does not look like a TLS handshake
2019/08/19 15:56:17 http: TLS handshake error from 10.107.19.62:59004: remote error: tls: bad certificate
2019/08/19 15:56:17 http: TLS handshake error from 10.107.19.62:59008: remote error: tls: bad certificate
2019/08/19 15:56:18 http: TLS handshake error from 10.107.19.62:59012: remote error: tls: bad certificate
2019/08/19 15:56:18 http: TLS handshake error from 100.113.129.235:46580: tls: first record does not look like a TLS handshake
2019/08/19 15:56:18 http: TLS handshake error from 10.107.19.62:59018: remote error: tls: bad certificate
2019/08/19 15:56:18 http: TLS handshake error from 10.107.19.62:59022: remote error: tls: bad certificate
2019/08/19 15:56:19 http: TLS handshake error from 100.113.129.235:46732: tls: first record does not look like a TLS handshake
```

I looked through past issues and saw the [following](https://github.com/aws/aws-app-mesh-inject/issues/63) issue. I reran the injector deployment with this command:

```
curl https://raw.githubusercontent.com/aws/aws-app-mesh-inject/master/scripts/install.sh | bash
```

However, I'm still running into the same issue. I'm running on EKS 1.13.7. Let me know if any other details are needed.

**Comment by streetmapp** [comment]
As an update, I followed the troubleshooting step and made sure to have a CA_BUNDLE environment variable ahead of running the install script, and that had the same results.

In comparing the value of caBundle in `mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-app-mesh-inject`, it appears the value that gets configured does _not_ match with the value that I have in my CA_BUNDLE environment variable. Once I apply the value that's in my environment variable, the injection works as expected.

**Comment by fmedery** [comment]
Hello @streetmapp , FYI I had the same problem but I just tested with the latest release of the injector and I don't have TLS error anymore.
