### ISSUE TITLE
404 when trying to retreave v0.1.6/scripts/deployInjector.sh

### ISSUE THREAD

**Issue by fmedery** [aws/aws-app-mesh-inject#73]
when running the bash script:
`https://raw.githubusercontent.com/aws/aws-app-mesh-inject/master/scripts/install.sh`

`curl https://raw.githubusercontent.com/aws/aws-app-mesh-inject/v0.1.6/scripts/deployInjector.sh`
return 404

**Comment by lavignes** [comment]
@fmedery hey sorry about that. I just cut a release tag for v0.1.6: https://github.com/aws/aws-app-mesh-inject/releases/tag/v0.1.6

**Comment by lavignes** [comment]
Feel free to re-open if it isn't working now. :-)
