### ISSUE TITLE
Inject mesh and virtual node name as annotations

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-inject#76]
Always inject the virtual node name and the mesh name so that the controller doesn't have to parse environment variables to discover them. See: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/53/files/e4b856d5bddec272689185d5eaf0efa34db04fdd#diff-8d4650ed46e8156bd1ea16a8212e7f76R122

**Comment by astrived** [comment]
@achevuru will be working on this

**Comment by achevuru** [comment]
Not applicable for GA version. VirtualNode name will be always available in the new version and we select pods based on podSelector in VirtualNode spec in v1beta2.
