### ISSUE TITLE
Support App Mesh Preview Channel

### ISSUE THREAD

**Issue by sviik** [aws/aws-app-mesh-inject#78]
https://docs.aws.amazon.com/app-mesh/latest/userguide/preview.html

One of the necessary steps for enabling App Mesh Preview Channel is
> Add APPMESH_PREVIEW = 1 as a configuration variable for the Envoy container

Currently the sidecar injector doesn't seem to support adding this env variable to the sidecar.

As App Mesh is in active development, then I'd assume that preview channel is used quite a lot, making this feature rather useful.

**Comment by bcelenza** [comment]
With the merge of #80 this is supported from the injector perspective. There's still remaining work in the controller (https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/75) to make it possible to create preview resources via the CRDs.

@sviik I'm going to close this issue, but please re-open if you think there's more to do on the injector side.
