### ISSUE TITLE
The condition of "AppendSidecar" isn't necessary since PodSpec requires at least one container

### ISSUE THREAD

**Issue by jqmichael** [aws/aws-app-mesh-inject#79]
https://github.com/aws/aws-app-mesh-inject/blob/efb9d8a97e95d0c305d5a59782cc4fbd07dbf1cc/pkg/webhook/server.go#L245

```
List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. Cannot be updated.
```
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#podspec-v1-core

**Comment by astrived** [comment]
@achevuru will be working on this

**Comment by achevuru** [comment]
Addressed in AppMesh controller GA version
