### ISSUE TITLE
Deprecate maddox/statsd-exporter

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-inject#82]
The Envoy image has been updated to v1.11 that has native Prometheus support for HTTP and gPRC metrics including latency `envoy_cluster_upstream_rq_time_bucket`. I think that the statsd-exporter sidecar is no longer needed.

@PaulMaddox do you agree on removing it or are there any metrics that are missing from Envoy native prom exporter?

**Comment by PaulMaddox** [comment]
Yes I agree, this can be removed now as the metrics are provided by the Prometheus exporter. I’ll open up a PR.
