### ISSUE TITLE
Add better configuration loading

### ISSUE THREAD

**Issue by jasonrichardsmith** [aws/aws-app-mesh-inject#93]
Many configurations are bound to cmd lines only.

The binary should be moved to something like Viper for config loading.
Or if we don't want that dependency just a plain yaml file loaded on start.

**Comment by stefanprodan** [comment]
I think the configuration should be done via Kubernetes custom resources, I plan to work on https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/34

**Comment by jamsajones** [comment]
Closed in favor of aws/aws-app-mesh-controller-for-k8s#34.
